package com.dsquare.db;

import java.util.ArrayList;
import java.util.List;

import com.dsquare.model.Exercise;

public interface ExerciseNamesBase {
    /**
     * The constant nazwyTreningów.
     * http://www.kulturystyka.pl/atlas/
     */
    String[] nameTrainings={
            "Wyciskanie sztangi sprzed głowy",
            "Wyciskanie sztangi zza głowy",
            "Wyciskanie sztangielek",
            "Arnoldki",
            "Unoszenie sztangielek bokiem w górę",
            "Unoszenie sztangielek w opadzie tułowia",
            "Podciąganie sztangi wzdłuż tułowia",
            "Podciąganie sztangielek wzdłuż tułowia",
            "Podciąganie kettlebell wzdłuż tułowia",
            "Unoszenie ramion w przód ze sztangą",
            "Unoszenie ramion w przód ze sztangielkami",
            "Unoszenie ramion ze sztangielkami w leżeniu",
            "Unoszenie ramion w przód z linkami wyciągu",
            "Unoszenie ramion bokiem w górę z linkami wyciągu",
            "Unoszenie ramion bokiem w górę w opadzie tułowia z linkami wyciągu",
            "Odwrotne rozpiętki",
            "Szrugsy z hantlami stojąc",
            "Szrugsy ze sztangą z przodu stojąc",
            "Szrugsy ze sztangą z tyłu stojąc",

            "Wyciskanie sztangi w leżeniu na ławce poziomej",
            "Wyciskanie sztangielek w leżeniu na ławce poziomej",
            "Wyciskanie sztangi w leżeniu na ławce skośnej-głową w górę",
            "Wyciskanie sztangielek w leżeniu na ławce skośnej-głową w górę",
            "Wyciskanie sztangi w leżeniu na ławce skośnej-głową w dół",
            "Wyciskanie sztangielek w leżeniu na ławce skośnej-głową w dół",
            "Rozpiętki ze sztangielkami w leżeniu na ławce poziomej",
            "Rozpiętki ze sztangielkami w leżeniu na ławce skośnej -głową do góry",
            "Wyciskanie sztangi w leżeniu na ławce poziomej wąskim uchwytem",
            "Przenoszenie sztangielki w leżeniu w poprzek ławki poziomej",
            "Pompki na poręczach",
            "Rozpiętki w siadzie na maszynie",
            "Krzyżowanie linek wyciągu w staniu",
            "Wyciskania poziome w siadzie na maszynie",
/*dodadkowe*/"Przenoszenie drążka nad głową na maszynie",

            "Podciąganie na drążku szerokim uchwytem (nachwyt)",
            "Podciąganie na drążku w uchwycie neutralnym",
            "Podciąganie na drążku podchwytem",
            "Podciąganie sztangi w opadzie (wiosłowanie)",
            "Podciąganie sztangielki w opadzie (wiosłowanie)",
            "Podciąganie końca sztangi w opadzie",
            "Przyciąganie linki wyciągu dolnego w siadzie płaskim",
            "Przyciąganie linki wyciągu górnego w siadzie",
            "Ściąganie drążka/rączki wyciągu górnego w siadzie szerokim uchwytem (nachwyt)",
            "Ściąganie drążka/rączki wyciągu górnego w siadzie podchwytem",
            "Ściąganie drążka/rączki wyciągu górnego w siadzie uchwyt neutralny",
            "Przenoszenie sztangi w leżeniu na ławce poziomej",
            "Podciąganie (wiosłowanie) w leżeniu na ławeczce poziomej",
            "Skłony ze sztangą trzymaną na karku",
            "Unoszenie tułowia z opadu",
            "Martwy ciąg",
            "Martwy ciąg na prostych nogach",
            "Wznosy barków Sztrugsy",
/*dodadkowe*/"Ściąganie rączki zza pleców na maszynie",

            "Przysiady ze sztangą na barkach",
            "Przysiady ze sztangą trzymaną z pzodu",
            "Hack-przysiady",
            "Przysiady na suwnicy skośnej (hack-maszynie)",
            "Syzyfki",
            "Prostowanie nóg w siadzie",
            "Wypychanie ciężaru na suwnicy (maszynie)",
            "Uginanie nóg w leżeniu",
            "Uginanie nóg w leżeniu na maszynie",
            "Przysiady wykroczne",
            "Nożyce",
            "Wysoki step ze sztangą/sztangielkami",
            "Odwodzenie nogi w tył",
            "Ściąganie kolan w siadzie",
            "Przywodzenie nóg do wewnątrz",
            "Odwodzenie nóg na zewnątrz",
            "Martwy ciąg",
            "Martwy ciąg na prostych nogach",

            "Wspięcia na palce w staniu",
            "Wspięcia na palce w staniu na maszynie",
            "Wspięcia na palce w siadzie",
            "Ośle wspięcia",
            "Wspięcia na palce na hack-maszynie",
            "Wypychanie ciężaru na maszynie/suwnicy palcami nóg",
            "Odwrotne wspięcia w staniu",

            "Skłony w leżeniu płasko",
            "Skłony w leżeniu głową w dół",
            "Unoszenie nóg w leżeniu na skośnej ławce",
            "Unoszenie nóg w zwisie na drążku",
            "Unoszenie nóg w podporze",
            "Spinanie Unoszenie kolan w leżeniu płasko",
            "Skłony tułowia z linką wyciągu siedząc",
            "Skręty tułowia",
            "Skłony tułowia z linką wyciągu klęcząc",
            "Skłony boczne",
            "Skłony boczne na ławce",
            "Skręty tułowia w leżeniu",

            "Uginanie ramion ze sztangą stojąc podchwytem",
            "Uginanie ramion ze sztangielkami stojąc podchwytem (z supinacją nadgarstka)",
            "Uginanie ramion ze sztangielkami stojąc (uchwyt młotkowy)",
            "Uginanie ramion ze sztangą podchwytem na modlitewniku",
            "Uginanie ramienia ze sztangielką na modlitewniku",
            "Uginanie ramion ze sztangielkami w siadzie na ławce skośnej (z supinacją nadgarstka)",
            "Uginanie ramienia ze sztangielką w siadzie - w podporze o kolano",
            "Uginanie ramion podchwytem stojąc-z rączką wyciągu",
            "Uginanie ramion ze sztangą nachwytem stojąc",
            "Uginanie ramion ze sztangą nachwytem na modlitewniku",
            "Uginanie nadgarstków podchwytem w siadzie",
            "Uginanie nadgarstków nachwytem w siadzie",
/*dodatkowe*/"Uginanie ramion naprzemiennie na modlitewniku na maszynie",
            "Uginanie ramion oburącz na modlitewniku na maszynie",
            "Podciąganie podchwytem",

            "Prostowanie ramion na wyciągu stojąc",
            "Wyciskanie francuskie sztangi w siadzie",
            "Wyciskanie francuskie jednorącz sztangielki w siadzie",
            "Wyciskanie francuskie sztangi w leżeniu",
            "Wyciskanie francuskie sztangielki w leżeniu",
            "Prostowanie ramienia ze sztangielką w opadzie tułowia",
            "Prostowanie ramion na wyciągu w płaszczyźnie poziomej stojąc",
            "Prostowanie ramion na wyciągu w płaszczyźnie poziomej w podporze",
            "Pompki na poręczach",
            "Pompki w podporze tyłem",
            "Prostowanie ramienia podchwytem na wyciągu stojąc",
            "Wyciskanie w leżeniu na ławce poziomej wąskim uchwytem",
/*dodadkowe*/"Prostowanie ramion na maszynie w górę",
/*dodadkowe*/"Prostowanie ramion na maszynie w dół"
    };

}

